service: express-app-lambda-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
    
plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true